// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6WyvIQh0j9gCV3KJyU8c-SCjuGiGUvTQ',
    appId: '1:49550759246:web:ffa16b7eed323a2e5cfa1f',
    messagingSenderId: '49550759246',
    projectId: 'flutter-testovoe',
    authDomain: 'flutter-testovoe.firebaseapp.com',
    storageBucket: 'flutter-testovoe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKqUqqXHyHv4MtZ_W1cQ9lkNC282AN1P0',
    appId: '1:49550759246:android:bc5f93d7df54c5c85cfa1f',
    messagingSenderId: '49550759246',
    projectId: 'flutter-testovoe',
    storageBucket: 'flutter-testovoe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3Sed62CANbG_gfrOEASdSByhWxVCXFU',
    appId: '1:49550759246:ios:17455c46d40bd9565cfa1f',
    messagingSenderId: '49550759246',
    projectId: 'flutter-testovoe',
    storageBucket: 'flutter-testovoe.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3Sed62CANbG_gfrOEASdSByhWxVCXFU',
    appId: '1:49550759246:ios:17455c46d40bd9565cfa1f',
    messagingSenderId: '49550759246',
    projectId: 'flutter-testovoe',
    storageBucket: 'flutter-testovoe.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6WyvIQh0j9gCV3KJyU8c-SCjuGiGUvTQ',
    appId: '1:49550759246:web:2576406a059d63735cfa1f',
    messagingSenderId: '49550759246',
    projectId: 'flutter-testovoe',
    authDomain: 'flutter-testovoe.firebaseapp.com',
    storageBucket: 'flutter-testovoe.appspot.com',
  );
}
